### ISSUE TITLE
Cart sync not working

### ISSUE THREAD

**Issue by ghost** [Vendic/magento2-external-checkout#3]
Is this compatible with new versions of VSF and magento 2.3? I did this setup in December, now I'm not able to work it out anymore.

What's the best approach here for above-mentioned setup? I see the instructions are a bit "old" as they are the same instructions I read before when I set it up.

I appreciate any help here.

**Comment by Tjitse-E** [comment]
The module should be compatible. Have you tried using it with https://github.com/Vendic/vsf-external-checkout?

**Comment by ghost** [comment]
> The module should be compatible. Have you tried using it with https://github.com/Vendic/vsf-external-checkout?

After playing around it worked.
```
    "externalCheckout": {
      "cmsUrl" : "https://cms.logima.io/checkout"
    },
```
In the module you made on magento:
<img width="939" alt="screen shot 2019-02-20 at 03 13 38" src="https://user-images.githubusercontent.com/41927878/53040958-b0bab480-34bd-11e9-91ea-2cf8ffebb7b1.png">

Before my cms URL on config was with the handle "vue/cart/sync". This seems to not apply in my case anymore.

This is with (what I assume is - downloaded it a week ago) VSF 1.8 and Magento 2.3. 

Love your work!
