### ISSUE TITLE
Not able to install module on 2.9 & 2.3.0

### ISSUE THREAD

**Issue by ghost** [Vendic/magento2-external-checkout#5]
Hi!

I've directly downloaded Magento's reps directly from their updated versions from github.

I tried installing the module on 2.9.0 and 2.3.0, both giving me this error:

> Problem 1
>     - Installation request for vuestorefront/magento2-vue-cart-sync ^2.0 -> satisfiable by vuestorefront/magento2-vue-cart-sync[2.0.0].
>     - vuestorefront/magento2-vue-cart-sync 2.0.0 requires magento/magento2-base ~2.2|~2.3 -> no matching package found.

In the beginning after running composer, it shows "Using version ^2.0 ", which doesn't give me a clue what version from what it is actually using, because the latest composer version is 1.8, php version is 7.2, and the magento version is 2.2 and 2.3 in both the versions which I've tried so I'm trying to figure out what this comment in the beginning after running the composer require command is referring to so that I can fix it but no search engine gives me any valid clues on how to fix it.

This module worked perfectly back in March when I installed it on magento 2.3 versions with the same exact prerequisites I tried with recently , but now I'm facing these error throwbacks which is quite a challenge to solve at the moment, not knowing if I'm downloading updated versions of magento which might inflict with this module at this current time, if that makes sense?

Appreciate the help here.

**Comment by Tjitse-E** [comment]
Hi! The latest release of the module is indeed [2.0](https://github.com/Vendic/magento2-external-checkout/releases). Did you install Magento 2 with compose? If so you should have the `magento/magento2-base` package installed, you can check with `composer show`

Another option is to download the latest release of the module, and move it to app/code/VueStorefront/CartSync, but then you don't have the benefits of composer.

**Comment by ghost** [comment]
Thank you!

First I downloaded magento 2.3.0 from Magento's github rep. Through normal installation I never found magento/magento2-base in vendor, but after installing the latest version of magento 2.3 with composer, the magento/magento2-base module showed up and I managed to install the external checkout.

Great that you answered fast!

**Comment by omercan** [comment]
I'm getting RuntimeException while intalling extension by moving extension files to app/code directory.

`root@mugo2headless-magento:/var/www/magento2# bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 52.0 MiB
                                                                                                                                   
  [RuntimeException]                                                                                                               
  Source class "\VueStorefront\CartSync\Service\Sync" for "\VueStorefront\CartSync\Service\SyncLogger" generation does not exist.  
                                                                                                                                   

setup:di:compile
`

@Tjitse-E
