### ISSUE TITLE
Unable to install vuestorefront/magento2-vue-cart-sync

### ISSUE THREAD

**Issue by razzul** [Vendic/magento2-external-checkout#9]
<pre><font color="#8AE234"><b>administrator@rajul</b></font>:<font color="#729FCF"><b>/var/www/html/magento2</b></font>$ composer require vuestorefront/magento2-vue-cart-sync:2.0.0
<font color="#4E9A06">./composer.json has been updated</font>
<font color="#4E9A06">Loading composer repositories with package information</font>
<font color="#4E9A06">Updating dependencies (including require-dev)</font>         
<span style="background-color:#CC0000"><font color="#D3D7CF">Your requirements could not be resolved to an installable set of packages.</font></span>

  Problem 1
    - Installation request for vuestorefront/magento2-vue-cart-sync 2.0.0 -&gt; satisfiable by vuestorefront/magento2-vue-cart-sync[2.0.0].
    - vuestorefront/magento2-vue-cart-sync 2.0.0 requires magento/magento2-base ~2.2|~2.3 -&gt; no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see &lt;https://getcomposer.org/doc/04-schema.md#minimum-stability&gt; for more details.
 - It&apos;s a private package and you forgot to add a custom repository to find it

Read &lt;https://getcomposer.org/doc/articles/troubleshooting.md&gt; for further common problems.

<span style="background-color:#CC0000"><font color="#D3D7CF">Installation failed, reverting ./composer.json to its original content.</font></span>
<font color="#8AE234"><b>administrator@rajul</b></font>:<font color="#729FCF"><b>/var/www/html/magento2</b></font>$</pre>

**Comment by Tjitse-E** [comment]
See #5
